version: "3.7"

services:
  db:
    image: postgres:13-alpine
    environment:
      POSTGRES_PASSWORD: postgres
      POSTGRES_USER: postgres
      POSTGRES_DB: etsyparser

  backend:
    build: .
    ports:
    - 8000:8000
    depends_on:
      - db
    env_file:
      - .env
