{{- if .Values.serviceAccount.create -}}
apiVersion: v1
kind: ServiceAccount
metadata:
  name: {{ include "etsy-parser.serviceAccountName" . }}
  labels:
{{ include "etsy-parser.labels" . | nindent 4 }}
{{- end -}}
