# Generated by Django 4.0.1 on 2022-01-14 10:48

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Parse',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('link', models.URLField(help_text='Ссылка для парсинга', verbose_name='Ссылка')),
                ('parse_date', models.DateTimeField(auto_now_add=True, verbose_name='parse date')),
                ('parse_file', models.FileField(upload_to='')),
            ],
            options={
                'ordering': ['-parse_date'],
            },
        ),
    ]
