# Generated by Django 4.0.1 on 2022-01-14 12:03

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('parse', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='parse',
            name='link',
            field=models.CharField(help_text='Ссылка для парсинга', max_length=200, verbose_name='Ссылка'),
        ),
    ]
