# Generated by Django 4.0.1 on 2022-01-14 12:12

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('parse', '0002_alter_parse_link'),
    ]

    operations = [
        migrations.CreateModel(
            name='Link',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('link', models.URLField(help_text='Ссылка для парсинга', verbose_name='Ссылка')),
            ],
        ),
        migrations.RenameField(
            model_name='parse',
            old_name='link',
            new_name='parse_link',
        ),
    ]
