# Generated by Django 4.0.1 on 2022-01-14 14:33

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('parse', '0003_link_rename_link_parse_parse_link'),
    ]

    operations = [
        migrations.AlterField(
            model_name='parse',
            name='parse_file',
            field=models.BinaryField(),
        ),
    ]
