# Generated by Django 4.0.1 on 2022-01-14 17:01

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('parse', '0004_alter_parse_parse_file'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='parse',
            name='parse_file',
        ),
        migrations.RemoveField(
            model_name='parse',
            name='parse_link',
        ),
        migrations.AddField(
            model_name='parse',
            name='parse_name',
            field=models.CharField(default='no-time', max_length=200),
        ),
        migrations.AlterField(
            model_name='link',
            name='link',
            field=models.URLField(max_length=500, verbose_name='Ссылка'),
        ),
    ]
