# Generated by Django 4.0.1 on 2022-01-17 07:13

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('parse', '0005_remove_parse_parse_file_remove_parse_parse_link_and_more'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Link',
        ),
        migrations.AddField(
            model_name='parse',
            name='link',
            field=models.URLField(default='', max_length=500, verbose_name='Ссылка'),
        ),
        migrations.AddField(
            model_name='parse',
            name='token',
            field=models.CharField(default='', max_length=200, verbose_name='Токен доступа'),
        ),
    ]
